### PR TITLE
Update base.html

### PR DESCRIPTION
**Pull request by debbiew27**
Capitalized self in "Remove self"

### CODE REVIEW

**Comment by ninaahmed** [comment]
Groundbreaking work, never been done before, never seen before, never imagined before.

**Comment by SamLab17** [comment]
What do you think this entails for the _User Experience_? This is a pretty drastic change to be making to the front-end of the website without alerting our users, they may have trouble finding their way around the site. Should we run a study before making such a prevalent change on the front end? Perhaps A/B testing?

**Review by ninaahmed — APPROVED** [review]

**Review by ClosingBracket — APPROVED** [review]

**Comment by ninaahmed** [comment]
> What do you think this entails for the _User Experience_? This is a pretty drastic change to be making to the front-end of the website without alerting our users, they may have trouble finding their way around the site. Should we run a study before making such a prevalent change on the front end? Perhaps A/B testing?

Maybe start with a 5% rollout?

**Comment by debbiew27** [comment]
> What do you think this entails for the _User Experience_? This is a pretty drastic change to be making to the front-end of the website without alerting our users, they may have trouble finding their way around the site. Should we run a study before making such a prevalent change on the front end? Perhaps A/B testing?

bruh

**Review by SamLab17 — APPROVED** [review]

**Pull request merged**
